version: '3'

services:
  ros2_ndi_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_ndi_tracker
    volumes:
      # Mount your ROM files directory
      - ./rom_files:/opt/ndi/rom_files
      # Mount your source code for development (optional)
      - ./src:/ros2_ws/src/ros2_ndi_tracker/ros2_ndi_tracker
      # Mount USB devices for NDI tracker
      - /dev:/dev
    devices:
      # Allow access to all devices
      - /dev/ttyUSB0:/dev/ttyUSB0  # Replace with your actual device path if different
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=1
    network_mode: host
    privileged: true
    command: ros2 run ros2_ndi_tracker ndi_tracker_node
